---
title: "On distance metrics of trees"
author: "GAO Zheng"
date: "February 7, 2017"
output:
  html_document:
    number_sections: true
    css: "~/Teaching/width.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Weighted graphs and distance metrics

If we have a graph $G = (V,E)$ on $n$ nodes, where $E \subseteq \{e_{ij},\;i,j\in I\}$ and $V = \{v_i,\;i\in I\}$, $I = \{1,2,\dots,n\}$. We only consider connected graphs here.

The graph is weighted if each $e_{ij} \in E$ is associated with a weight $w_{ij}\ge0$, with $w_{ii}=0\;\text{ for all }i\in I$.

The weighted graph induces a distance metric $d^*$

$$
  d^*_{ij} =
  \begin{cases}
    w_{ij},&\;\text{if }\;e_{ij}\in E \\
    \infty & \text{otherwise}
  \end{cases}
$$

If we define a 'multiplication'

$$
((d^*)^2)_{ij} = \min_{k}\{d^*_{ik}+d^*_{kj}\}
$$

then raising $d^*$ to the $n^{th}$ power will produce a matrix without $\infty$-entries; ${d^*}^{n+1} = {d^*}^{n} := d$, since the graph is connected, and every node can be reached from any other within $n$ steps.

The distance metric $d$ (first of all, is a valid distance metric,) has the interpretation of shortest distance travelling from one node to another on the graph.

Some prpoerties worth-noting are:

1. Any valid distance metric on $n$ nodes can be represented by a weighted graph 
^[Hakimi, S. L. and Yau, S. S., "Distance matrix of a graph and its realizability." Quarterly of Applied Mathematics, Vol. 22, No. 4 (JANUARY, 1965), pp. 305-317] 
^[Goldman, A. J. "Realizing the distance matrix of a graph." J. Res. Nat. Bur. Standards Sect. B 70 (1966): 153-154.].

2. The space distance metrics form a polyhedral cone (by usual addition and scalar multiplication of matrices). Its extreme rays have been described.
^[Avis, David. "On the extreme rays of the metric cone." Canadian Journal of Mathematics 32.1 (1980): 126-144.]

One way to look at the problem, as Divid Avis pointed out, may to write out the n triangular inequalities for each $(i,j)$ pair, with non-negativity constraints and $d_{ii}=0$, and to characterize the cone using a system of inequalities $A\overrightarrow{d}\le b$, where $\overrightarrow{d}$ is the vectorized distance metric.

# Weighted trees and distance metrics

In a similar fashion, we can construct distance metrics from weighted trees. Denote the space of all distance metrics generated by trees $D_\mathcal{T}$. Note that one may add edges to a tree without affecting the distance metric.

Aside from 1 and 2, we also have

3. Distance matrices of trees has a one-to-one mapping to weighted trees; see [here](./tree_distance_matrix.html) for a simple recovery algorithm. So we can know that

4. Trees of the same topology form a polyhedral convex cone (addition of distance metrics do not introduce new edges that did not exist).

A characterization of $D_\mathcal{T}$ is given by the 4-point condition.^[Buneman, Peter. "A note on the metric properties of trees." Journal of Combinatorial Theory, Series B 17.1 (1974): 48-50.]

In some sense the requirement for a distance metric to correspond to a tree is much more stringent; there are a lot of tight contraint in $A\overrightarrow{d}\le b$. In particular, a facet corresponds to $1$ tight constraint, an extreme ray corresponds to $n-1$ tight constraints for distance metrics.

It would be interesting to find out the geometry of the tree cones, and where they lie in the cone of general metrics.


# Questions:

Some questions that arise are

## Q1. Can all distance metrics be generated (through addition, scalar multiplication) by $D_\mathcal{T}$?

A1. No.

For 3 nodes, the extremal rays are trees (one edge degenerate), so trees do generate all distance metrics.

For 5 nodes, a counter-example can be found in David's paper. A particular extremal ray was found, but is not a tree.

## Q2. Are all $d \in D_\mathcal{T}$ on extremal rays?

A2. No

For example, two 3 node trees with $d^{(1)}_{13}=d^{(1)}_{12}+d^{(1)}_{23}$,  $d^{(2)}_{13}=d^{(2)}_{12}+d^{(2)}_{23}$, and  $d^{(1)}_{12}=1$, $d^{(1)}_{23}=2$, $d^{(2)}_{12}=2$, $d^{(2)}_{23}=1$.

Then $d^{(3)} = d^{(1)}+d^{(2)}$ is a tree, but not a constant multiple of either.

In fact, by the same argument, no tree can be an extremal ray of the cone. (Since all trees can be expressed as a convex combination of two trees 'perturbed' in the opposite direction. again, like all statements in this document, need to be made precise.)

## Q3. Are trees on the facets?

I.e., there cannot be an open ball around a $d\in D_\mathcal{T}$ that is contained in the cone of distance metrics.

idk. My guess would be yes.

## Q4. If we have a fuzzy measurement $d+\epsilon$ of distance metric $d\in D_\mathcal{T}$, can we recover the tree?

idk. The statement is not well-formulated yet.

## Q5. Is the concept of spanning tree / max spanning tree useful?

idk.

## Q6. Can we define something like a 'basis' for $D_\mathcal{T}$, convex combination of $D_\mathcal{T}$, or space of all distance metrics $D$?

idk. My guess would be "not if we require orthogonality in the usual sense". There might be hope for another kind of basis. 